[package]
name = "repetitions"
version = "0.1.0"
authors = ["Ben Silverman <bensilverman10@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
